# Generated by Django 2.0 on 2018-03-28 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_grapher', '0002_auto_20160729_1242'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_id', models.IntegerField(default=0)),
                ('band_id', models.IntegerField(default=0)),
                ('album_name', models.CharField(max_length=50)),
                ('score_avg', models.IntegerField(default=50)),
                ('date', models.DateTimeField()),
                ('review_summary', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_id', models.IntegerField(default=0)),
                ('review', models.CharField(max_length=5000)),
                ('score', models.IntegerField(default=50)),
                ('key_words', models.CharField(max_length=1000)),
                ('band_comparisons', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='band',
            name='band_avg',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='band',
            name='band_divisiveness',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='band',
            name='band_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='band',
            name='regression',
            field=models.IntegerField(default=0),
        ),
    ]
