# Generated by Django 2.0 on 2018-04-01 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_grapher', '0006_auto_20180401_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_id', models.IntegerField(default=0)),
                ('review', models.CharField(max_length=5000)),
                ('publication', models.CharField(max_length=50)),
                ('score', models.IntegerField(default=50)),
                ('review_link', models.IntegerField(default=50)),
                ('key_words', models.CharField(max_length=1000)),
                ('band_comparisons', models.CharField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='Reviews',
        ),
        migrations.AddField(
            model_name='album',
            name='genre',
            field=models.CharField(default='x', max_length=50),
        ),
        migrations.AddField(
            model_name='album',
            name='label',
            field=models.CharField(default='x', max_length=50),
        ),
        migrations.AddField(
            model_name='album',
            name='number_critic_reviews',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='album',
            name='number_user_reviews',
            field=models.IntegerField(default=0),
        ),
    ]
